# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
        displayName: 'Use Python $(python.version)'
      - script: |
          which python
          echo 'Working directory is supposed to be : '
          echo '$(Build.Repository.LocalPath)'
          echo 'Current wd is :'
          pwd
          ls -al
          
          python -m pip install --upgrade pip
          python -m venv env
          source env/bin/activate
          
          echo 'After sourcing, it is :'
          pwd
          ls -al
          
          pip install -r requirements.txt
          
          echo 'After installing, it is :'
          pwd
          ls -al
          echo 'Env folder after installing requirement is :'
          pwd
          ls -al env
        workingDirectory: '$(Build.Repository.LocalPath)'
        displayName: 'Install dependencies'
      # - script: |
      #     pip install pytest pytest-azurepipelines
      #   workingDirectory: '$(Build.Repository.LocalPath)'
      #   displayName: 'pytest'

  - job: Deploy
    dependsOn: Build
    steps:
    - task: CopyFiles@2
      displayName: 'Copy files'
      inputs:
        sourceFolder: '$(Build.Repository.LocalPath)'
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
