# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Deploy
    # dependsOn: Build
    steps:
    - task: CopyFiles@2
      displayName: 'Copy files'
      inputs:
        sourceFolder: '$(Build.Repository.LocalPath)'
        contents: |
          **/*
          !.git/**/*
        targetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
